### ISSUE TITLE
Units not accepted by scenario explorer

### ISSUE THREAD

**Issue by EmiFej** [OSeMOSYS/osemosys2iamc#39]
The units for Capital Cost are reported in the config file as `MEUR_2015/GW`. When uploading results in IAMC obtained by using the osemosys2iamc, it is not possible to upload them to the ECEMF Scenario Explorer since it requests the unit for Capital Cost to be given in `EUR_2020/kW` or  `USD_2010/kW`.

Should this be changed in the config file?

**Comment by HauHe** [comment]
This is addressed by PR #37
