### ISSUE TITLE
Converting ISO codes into country names

### ISSUE THREAD

**Issue by HauHe** [OSeMOSYS/osemosys2iamc#5]
Often we work with ISO codes either ISO2 or ISO3 in OSeMOSYS models. 
At some point in the conversion of OSeMOSYS results into IAMC format the country codes need to be converted into full country names. 
The openEntrance nomenclature package there is the option to convert ISO codes into country names using `iso_mapping[]`https://github.com/openENTRANCE/nomenclature/tree/master/nomenclature/definitions/region
I tried to apply it on the region index of the IAMC dataframe just before saving it as csv. However, I got somewhat stuck. the column `region` is part of a multiindex, which seems to make it difficult to call it. But I also couldn't find a way to use the function `iso_mapping` on a list or dataframe column. Any suggestions how to proceed?

**Comment by willu47** [comment]
Should be something like:

```python
df = df.reset_index()
df['country'] = nc.iso_mapping(df['country'])
df.set_index(['country', 'another_column', 'other_column']
```

If that doesn't work, perhaps nc.iso_mapping won't accept a dataframe column as an argument, then you can use `df['country'].apply(lambda x: nc.iso_mapping(x))`

**Comment by HauHe** [comment]
Thanks for having a look! 
Actually solved it already, see the penultimum commit on the PR.
