### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by HauHe** [OSeMOSYS/osemosys2iamc#6]
The IIASA scenario takes only xlsx files. 
Therefore, it would be convenient to safe the output as xlsx instead of csv.
Furthermore, the sheets need to be called something with data, e.g. `data` but there can be several `data1``data2`and so on.

**Comment by willu47** [comment]
Should be as simple as changing [this](https://github.com/OSeMOSYS/osemosys2iamc/blob/2f3e7ae9180cac84b4fd138b556cb76d572003d4/resultify.py#L95) line to [`to_excel`](https://pyam-iamc.readthedocs.io/en/stable/api/io.html)

**Comment by HauHe** [comment]
Thanks for the point out Will!
Will implement and push it later.
